apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w2nq2hdlg-python 
  janus-idp.io/tekton: w2nq2hdlg-python
  backstage.io/kubernetes-id: w2nq2hdlg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w2nq2hdlg-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  